// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjj4Gu-my6wo2rDuDY9x_RM7_G5616F3U',
    appId: '1:674164624386:web:ca229fd4d6fc4291b32b1b',
    messagingSenderId: '674164624386',
    projectId: 'myapp-8fb3f',
    authDomain: 'myapp-8fb3f.firebaseapp.com',
    storageBucket: 'myapp-8fb3f.firebasestorage.app',
    measurementId: 'G-2BEW6YQH8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0DP1XS0TirbW7iwzeBH-V1ui9mlD-35M',
    appId: '1:674164624386:android:3d941ce9e13366b8b32b1b',
    messagingSenderId: '674164624386',
    projectId: 'myapp-8fb3f',
    storageBucket: 'myapp-8fb3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqxoZSgVTaeAx9T4fu4uMM5QWvOJodO_Y',
    appId: '1:674164624386:ios:a82421d17844a189b32b1b',
    messagingSenderId: '674164624386',
    projectId: 'myapp-8fb3f',
    storageBucket: 'myapp-8fb3f.firebasestorage.app',
    iosBundleId: 'com.example.drivingTestPrep',
  );
}
